name: Glitch Deploy

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  glitch-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Sync Glitch repository with GitHub
      uses: kanadgupta/glitch-sync@v1.1
      with:
        project-id: '${{ secrets.GLITCH_PROJECT_ID }}'
        auth-token: '${{ secrets.GLITCH_AUTHORIZATION }}'
