name: Glitch Sync

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  glitch-sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Synchronize Glitch project with GitHub
      uses: kanadgupta/glitch-sync@v1.1
      with:
        project-id: '${{ secrets.GLITCH_PROJECT_ID }}'
        auth-token: '${{ secrets.GLITCH_AUTHORIZATION }}'
